// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxArNYKT8SJTG7TDzs-GT01wMADE9Ayk4',
    appId: '1:99956174618:web:e9b9bc34378bc51c3846a3',
    messagingSenderId: '99956174618',
    projectId: 'tiktok-8814b',
    authDomain: 'tiktok-8814b.firebaseapp.com',
    storageBucket: 'tiktok-8814b.appspot.com',
    measurementId: 'G-F5SB3L3XCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG0174YPDwVRRCKwwBhNEcHP5gGn-H-9o',
    appId: '1:99956174618:android:fff909d323bb6e743846a3',
    messagingSenderId: '99956174618',
    projectId: 'tiktok-8814b',
    storageBucket: 'tiktok-8814b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOa59EN76O0Yq6aXsLWTEyHOYzo6ChpCo',
    appId: '1:99956174618:ios:f2784fff1cce50fc3846a3',
    messagingSenderId: '99956174618',
    projectId: 'tiktok-8814b',
    storageBucket: 'tiktok-8814b.appspot.com',
    iosClientId: '99956174618-402erom8523nd22lpd122qa9qsaf8lnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOa59EN76O0Yq6aXsLWTEyHOYzo6ChpCo',
    appId: '1:99956174618:ios:f2784fff1cce50fc3846a3',
    messagingSenderId: '99956174618',
    projectId: 'tiktok-8814b',
    storageBucket: 'tiktok-8814b.appspot.com',
    iosClientId: '99956174618-402erom8523nd22lpd122qa9qsaf8lnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
